name: Auto Assign to Project

on:
  pull_request:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.WORKFLOW_ORG_ACCESS_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign new opened pull requests to Project
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/snipcart/projects/9'
        column_name: '⏳ In progress'
